services:
  webtop:
    image: lscr.io/linuxserver/webtop:arch-xfce
    container_name: webtop-arch-xfce
    privileged: true #optional for KDE or i3
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Netherlands
      - SUBFOLDER=/ #optional
    volumes:
      - ./data:/config
      # - /var/run/docker.sock:/var/run/docker.sock #optional for docker inside docker
    ports:
      - 13390:3000
    shm_size: "1gb" #optional
    restart: unless-stopped