version: "2.1"

services:
  nextcloud:
    image: linuxserver/nextcloud:23.0.0-php8
    container_name: nextcloud
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=Europe/Netherlands
      # - REDIS_HOST=redis-nextcloud
      # - REDIS_HOST_PASSWORD=YOURREDISPASSWORD
    volumes:
      - ./appdata:/config
      - ./data:/data
      # - ./nextcloud.ini:/etc/php8/conf.d/nextcloud.ini
    ports:
      - 13370:443
    restart: unless-stopped
    depends_on:
      - postgres-nextcloud
      # - redis-nextcloud

  postgres-nextcloud:
    image: postgres:14.1-alpine
    container_name: postgres-nextcloud
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=YOURPASSWORD
    volumes:
      - ./DB:/var/lib/postgresql/data

  # redis-nextcloud:
  #   image: redis:alpine
  #   container_name: redis-nextcloud
  #   command: redis-server --requirepass YOURREDISPASSWORD
  #   restart: unless-stopped
