version: "3.1"

services:
  db:
    image: mariadb:latest
    container_name: MariaDB-Host1
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=YOURPASSWORD"
      - "MYSQL_PASSWORD=YOURPASSWORD"
      - "MYSQL_DATABASE=YOURUSER"
      - "MYSQL_USER=YOURUSER"
    ports:
      - 10000:3306
    volumes:
      - ./DB:/var/lib/mysql
      #- ./app.cnf:/etc/mysql/conf.d/app.cnf
