version: "3"

services:
  socks5_ipv4:
    image: olebedev/socks5
    container_name: socks5_ipv4
    restart: unless-stopped
    ports:
      - 28131:1080
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - PROXY_USER=YOURUSER
      - PROXY_PASSWORD=YOURPASSWORD
#    security_opt:
#      - no-new-privileges:true
