version: "3"

services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: 1000:1000
    restart: unless-stopped
#    ports:
#      - 11000:80
    volumes:
      - ./data:/srv
      - ./filebrowser.db:/filebrowser.db
      - ./settings.json:/settings.json
    security_opt:
      - no-new-privileges:true
    networks:
      - default

networks:
  default:
    external: true
    name: evilcorp