version: '3.1'

services:
  db:
    image: mariadb:10.5.12-focal
    restart: unless-stopped
    environment:
      - 'MYSQL_ROOT_PASSWORD=YOURPASSWORD'
      - 'MYSQL_PASSWORD=YOURPASSWORD'
      - 'MYSQL_DATABASE=domain-parser'
      - 'MYSQL_USER=domain-parser'
    ports:
      - 10001:3306
    volumes:
      - ./DB:/var/lib/mysql