version: "2.1"

services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud:arm64v8-version-22.1.1
    container_name: nextcloud
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Netherlands
    volumes:
      - ./appdata:/config
      - ./data:/data
    ports:
      - 13370:443
    restart: unless-stopped