version: "2.1"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Netherlands
      - SERVERURL=auto # wireguard.domain.com
      - SERVERPORT=51820
      - PEERS=1 #optional
      - PEERDNS=auto # auto 
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS=all #optional 1,4,laptop
      - LOG_CONFS=false #optional
    volumes:
      - /app/vpn/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
#    dns:
#      - 1.1.1.1
#      - 8.8.8.8
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
