version: "2.1"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss
    container_name: freshrss
    environment:
      # - PUID=1337
      # - PGID=1337
      - TZ=Europe/London
    volumes:
      - ./data:/config
    ports:
      - 13380:80
    restart: unless-stopped