version: "3.1"

services:
  db:
    image: mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=YOURPASSWORD"
      - "MYSQL_PASSWORD=YOURPASSWORD"
      - "MYSQL_DATABASE=publicproxy"
      - "MYSQL_USER=publicproxy"
    ports:
      - 10000:3306
    volumes:
      - /app/publicproxy-db/DB:/var/lib/mysql
